name: Compliance check and build test

env:
  npm-path: frontend

on: # defining on which triggers this action should run
  push:
  
jobs:
  build-maven:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.npm-path }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm 
          cache-dependency-path: "${{ env.npm-path }}/package-lock.json"
      - name: Install dependencies
        run: npm ci # or pnpm install / yarn install / bun install
      - name: Run lint
        run: npm run lint
      - name: Run test
        run: npm run test:unit      
      - name: Run build
        run: npm run build
